set(CPM_DOWNLOAD_VERSION 0.40.8)
set(CPM_DOWNLOAD_LOCATION "${CMAKE_BINARY_DIR}/cmake/CPM_${CPM_DOWNLOAD_VERSION}.cmake")
set(CPM_DOWNLOAD_HASH "78ba32abdf798bc616bab7c73aac32a17bbd7b06ad9e26a6add69de8f3ae4791")

set(CPM_DOWNLOAD_REQUIRED TRUE)
if(EXISTS "${CPM_DOWNLOAD_LOCATION}")
  file(SHA256 "${CPM_DOWNLOAD_LOCATION}" CPM_EXISTING_HASH)
  if(CPM_EXISTING_HASH STREQUAL CPM_DOWNLOAD_HASH)
    set(CPM_DOWNLOAD_REQUIRED FALSE)
  endif()
endif()

if(CPM_DOWNLOAD_REQUIRED)
  message(STATUS "Downloading CPM.cmake ${CPM_DOWNLOAD_VERSION}")
  file(
    DOWNLOAD
      "https://github.com/cpm-cmake/CPM.cmake/releases/download/v${CPM_DOWNLOAD_VERSION}/CPM.cmake"
      "${CPM_DOWNLOAD_LOCATION}"
    EXPECTED_HASH SHA256=${CPM_DOWNLOAD_HASH}
  )
endif()

include("${CPM_DOWNLOAD_LOCATION}")
